"""Flask demo: a localhost app that walks one patient through the pipeline.

Run:  python3 app.py   then open http://127.0.0.1:5000

Tabs (see GOAL.md):
  1. Diagnose - watch a real LLM work a case turn by turn through the SDBench-style
     gatekeeper; switch the agent design and see the workup change.
  2. Deliver  - score the ordered tests, deliver one as an alert, simulated clinician
     with alert fatigue.
  3. Policy   - adaptive delivery policy over a stream vs naive rules.

The LLM runs server-side via shared/llm.py (key in demo/.env). No key -> deterministic
stub, labelled offline. Reuses the reference modules in 0X_*/demo_*.py.
"""

from __future__ import annotations

import glob
import hashlib
import json
import os
import re
import sys
import uuid

from flask import Flask, jsonify, render_template, request, session

HERE = os.path.dirname(os.path.abspath(__file__))
# Stage modules live in numbered subdirs. The separator drifts between '_' and '-' on this
# network mount, so glob for the numbered dirs instead of hardcoding names.
sys.path.insert(0, HERE)
for sub in sorted(glob.glob(os.path.join(HERE, "0[0-9]?*"))):
    if os.path.isdir(sub):
        sys.path.insert(0, sub)

from shared import llm  # noqa: E402
from shared.toy_data import load_case, CASES  # noqa: E402
from cpc.cpc_data import CPCS as SAMPLE_CPCS  # noqa: E402  (real CPC-Bench cases if present, else samples)
from demo_environment import SequentialDiagnosisEnv, _case_file  # noqa: E402
import demo_generation as G  # noqa: E402
from demo_scoring import score_recommendation  # noqa: E402

import store  # noqa: E402  (SQLite study store — see store.py)

app = Flask(__name__)
app.secret_key = os.environ.get("STUDY_SECRET", "demo-not-secret")
app.config["TEMPLATES_AUTO_RELOAD"] = True      # re-read templates on edit even in prod mode
store.init()

# Models the agent can run on (any OpenRouter id the key can reach). Default = .env.
DEFAULT_MODEL = os.environ.get("OPENROUTER_MODEL", "meta-llama/llama-3.3-70b-instruct")
MODELS = [
    {"id": DEFAULT_MODEL, "label": DEFAULT_MODEL.split("/")[-1]},
    {"id": "meta-llama/llama-3.2-3b-instruct", "label": "llama-3.2-3b (small)"},
    {"id": "openai/gpt-4o-mini", "label": "gpt-4o-mini"},
    {"id": "google/gemini-2.0-flash-001", "label": "gemini-2.0-flash"},
]
# de-dup if the env model is already one of the extras
_seen = set()
MODELS = [m for m in MODELS if not (m["id"] in _seen or _seen.add(m["id"]))]

# ---- case registry ---------------------------------------------------------
# A small curated set: the structured EHR cases + one narrative CPC.
CPC_BY_ID = {c.case_id: c for c in SAMPLE_CPCS}
_CPC_PICK = SAMPLE_CPCS[0].case_id if SAMPLE_CPCS else None

# Real MIMIC-IV admissions (built by build_mimic_cases.py): structured cases with a real principal
# ICD diagnosis and real lab results served by the gatekeeper. MIMIC_ORDERS holds the real order set
# per case, for the ordering-concordance metric ("was the recommended test actually measured?").
from cpc.cpc_data import CPCCase  # noqa: E402
MIMIC_BY_ID, MIMIC_ORDERS = {}, {}
try:
    for _cid, _c in json.load(open(os.path.join(HERE, "data", "mimic_cases.json"))).items():
        MIMIC_BY_ID[_cid] = CPCCase(case_id=_cid, abstract=_c["abstract"], case_file=_c["case_file"],
                                    true_diagnosis=_c["true_dx"], presentation=_c.get("presentation", ""))
        MIMIC_ORDERS[_cid] = set(_c.get("orders", []))
except Exception:
    pass

# Pre-recorded agent conversations (generated by record.py). The agent runs are static
# replays; only the clinician-driven path calls the model live. {} until record.py runs.
RECORDINGS_PATH = os.path.join(HERE, "data", "recordings.json")
REC_DIR = os.path.join(HERE, "data", "recordings")       # per (model, prompt-version) files live here
INDEX_PATH = os.path.join(REC_DIR, "index.jsonl")        # append-only run log (one row per run)
try:
    with open(RECORDINGS_PATH) as _f:
        RECORDINGS = json.load(_f)
except Exception:
    RECORDINGS = {}


def all_case_options():
    opts = [{"id": cid, "mode": "ehr",
             "label": f"{c.case_id} - {c.abstract[:60]}..."} for cid, c in CASES.items()]
    for c in SAMPLE_CPCS:
        opts.append({"id": c.case_id, "mode": "cpc",
                     "label": f"{c.case_id} (CPC) - {c.abstract[:55]}..."})
    for cid, c in MIMIC_BY_ID.items():
        opts.append({"id": cid, "mode": "mimic",
                     "label": f"{cid} (MIMIC) - {c.abstract[:50]}..."})
    return opts


def load_any(case_id):
    if case_id in CASES:
        return load_case(case_id), "ehr"
    if case_id in CPC_BY_ID:
        return CPC_BY_ID[case_id], "cpc"
    if case_id in MIMIC_BY_ID:
        return MIMIC_BY_ID[case_id], "mimic"
    raise KeyError(case_id)


# ---- per-session env store (in memory; the Benchmark turns are durably logged in SQLite) ----
SESSIONS: dict[str, dict] = {}


def _sid():
    if "sid" not in session:
        session["sid"] = uuid.uuid4().hex
    return session["sid"]


def _pid():
    return session.get("pid")


def _attribution():
    """The (session_id, pid) every study event is tagged with."""
    return {"session_id": _sid(), "pid": _pid()}


def _state():
    return SESSIONS.get(_sid())


def _is_cpc(case):
    return getattr(case, "case_file", None) is not None


def _make_env(case, gatekeeper="auto"):
    """Gatekeeper: rule-based for structured EHR, LLM-backed for narrative cases.
    `gatekeeper` may be 'rule' | 'llm' | 'auto'. CPC narratives have no panels, so
    they always use the LLM gatekeeper regardless of the request."""
    use_llm = _is_cpc(case) or gatekeeper == "llm"
    return SequentialDiagnosisEnv(case=case, llm_gatekeeper=use_llm)


def full_vignette(case):
    """The complete case for DISPLAY (reviewer's 'view full case'). The gatekeeper holds the real
    case_file with the confidential diagnosis; we strip that line so it's never shown."""
    cf = getattr(case, "case_file", None) or _case_file(case)
    return cf.split("\n\nFINAL DIAGNOSIS (CONFIDENTIAL")[0].rstrip()


# ---- one agent turn (ported from demo_generation, single step) -------------

# Three designs spanning the complexity axis we're testing: one plain call, one call that
# role-plays every relevant role, and a genuine multi-agent system where separate LLM calls
# deliberate before acting. The question: does the expensive multi-agent scaffolding pay off?
DESIGNS = {
    "single": ("LLM", G.BASELINE_SYSTEM, "baseline"),          # baseline: "recommend a test"
    "maidxo": ("LLM-Roles", G.PANEL_SYSTEM, "baseline"),       # 1 call, same format + "consider these roles"
    "debate": ("LLM-Multi", "", "debate"),                    # N advocate calls + coordinator
}

# --- Genuine multi-agent debate: each Quadruple-Aim advocate is its OWN LLM call (independent
# position), then a coordinator call reconciles them into one action. Not one prompt role-playing. ---
DEBATE_ADVOCATES = {
    "Hypothesis": "You are Dr. Hypothesis on a diagnostic panel. You maintain a probability-ranked "
                  "differential of the three most likely conditions, updating their probabilities in a "
                  "Bayesian way as new findings emerge. Propose the ONE next action that best reduces "
                  "your diagnostic uncertainty.",
    "Test-Chooser": "You are Dr. Test-Chooser. You select the diagnostic test that best DISCRIMINATES "
                    "among the leading hypotheses. Propose the ONE next test (or question) with the "
                    "highest discriminating value.",
    "Challenger": "You are Dr. Challenger, the panel's devil's advocate. You identify anchoring bias, "
                  "highlight evidence that contradicts the leading diagnosis, and propose a test that "
                  "could FALSIFY it. Propose the ONE next action that best guards against a premature or "
                  "wrong diagnosis.",
    "Stewardship": "You are Dr. Stewardship. You promote cost-conscious care: recommend lower-cost "
                   "alternatives when diagnostically equivalent and veto expensive tests with low "
                   "expected yield. Propose the ONE next action that gets the needed information at least cost.",
    "Checklist": "You are Dr. Checklist, silent quality control. You ensure test names are valid and the "
                 "panel's reasoning stays internally consistent. Propose the ONE next action, flagging "
                 "any invalid test name or inconsistency.",
}
_ADVOCATE_FMT = ('\nA TEST is an investigation; a DIAGNOSIS is a disease name (never a test). Reply with ONLY '
                 'JSON: {"action":"ask|test|diagnose","query":"<question, test name, or disease>","dx":'
                 '"<your single best diagnosis guess>","why":"<one line>"}.')
DEBATE_COORD = (
    "You are the COORDINATOR of a virtual diagnostic panel (MAI-DxO style). Five specialists — "
    "Dr. Hypothesis (probability-ranked differential), Dr. Test-Chooser (discriminating tests), "
    "Dr. Challenger (devil's advocate), Dr. Stewardship (cost), and Dr. Checklist (quality control) — "
    "each proposed a next action. Reconcile them into the ONE best action: take the diagnostically "
    "necessary step that best discriminates the leading hypotheses, by the least-cost valid means, after "
    "weighing the Challenger's objections. When you diagnose, name the SPECIFIC disease/etiology (not a "
    "syndrome category). Reply with ONLY JSON: "
    '{"differential":[{"dx":str,"p":float}],"debate":"<2-3 sentence synthesis of the specialists>",'
    '"action":"ask|test|diagnose","query":str|null,"diagnosis":str|null}')


# ---- content-addressed run identity ----------------------------------------
# A run is defined by its INPUTS: model, the exact prompt text, the case, and the
# environment config. We key on a fingerprint of those, so editing a prompt forks a
# new key (old runs are kept, never clobbered) and identical specs dedup for free.

def _model_slug(model):
    return re.sub(r"[^a-z0-9._-]+", "-", (model or DEFAULT_MODEL).lower()).strip("-")


def design_prompt_text(design):
    """The canonical prompt text that DEFINES a design — the source of its fingerprint.
    For 'debate' the prompt is assembled from the advocate + coordinator prompts."""
    if design == "debate":
        parts = [DEBATE_COORD, _ADVOCATE_FMT] + [v for _, v in sorted(DEBATE_ADVOCATES.items())]
        return "\n\n".join(parts)
    return (DESIGNS.get(design, (None, "", None))[1]) or ""


def prompt_fp(design):
    """8-char fingerprint of a design's prompt. Changes iff the prompt wording changes."""
    return hashlib.sha256(design_prompt_text(design).encode("utf-8")).hexdigest()[:8]


def run_key(model, design, case_id, gatekeeper="auto", max_turns=None):
    """12-char content key uniquely identifying a run's full spec."""
    spec = "|".join([model or "", design, prompt_fp(design), case_id,
                     gatekeeper or "auto", str(MAX_TURNS if max_turns is None else max_turns)])
    return hashlib.sha256(spec.encode("utf-8")).hexdigest()[:12]


def run_file(model, design):
    """New layout: one file per (model, prompt-version) = data/recordings/<model>/<design>@<fp>.json"""
    return os.path.join(REC_DIR, _model_slug(model), f"{design}@{prompt_fp(design)}.json")


def iter_runs():
    """Yield (model, design, fp, case_id, run) across the new AND legacy layouts, deduped.

    New:    data/recordings/<model>/<design>@<fp>.json   = {case: run}
    Legacy: data/recordings/<model>.json                 = {case: {design: run}}
    The new layout wins on collision (same model/design/case)."""
    seen = set()
    for path in glob.glob(os.path.join(REC_DIR, "*", "*@*.json")):       # new, preferred
        model = os.path.basename(os.path.dirname(path))
        design, _, fp = os.path.basename(path)[:-5].partition("@")
        try:
            recs = json.load(open(path))
        except Exception:
            continue
        for cid, run in recs.items():
            if isinstance(run, dict) and (model, design, cid) not in seen:
                seen.add((model, design, cid))
                yield model, design, fp, cid, run
    for path in glob.glob(os.path.join(REC_DIR, "*.json")):              # legacy aggregate
        model = os.path.basename(path)[:-5]
        try:
            recs = json.load(open(path))
        except Exception:
            continue
        for cid, designs in recs.items():
            if not isinstance(designs, dict):
                continue
            for design, run in designs.items():
                if isinstance(run, dict) and (model, design, cid) not in seen:
                    seen.add((model, design, cid))
                    yield model, design, (run.get("meta") or {}).get("prompt_fp", ""), cid, run


def _debate_turn(env, model=None, final=False):
    """One turn of genuine multi-agent debate: N advocate calls + 1 coordinator call."""
    obs = env.observation() + "\n\n" + _orderable(env) + "\nTake one action."
    final_hint = "\nThis is the FINAL turn: your action MUST be 'diagnose'." if final else ""

    proposals = []                                       # each advocate votes independently
    for name, sys_prompt in DEBATE_ADVOCATES.items():
        try:
            rec = G._extract_json(llm.chat(
                [{"role": "system", "content": sys_prompt + _ADVOCATE_FMT + final_hint},
                 {"role": "user", "content": obs}], model=model, max_tokens=200))
        except Exception:
            rec = {}
        proposals.append((name, rec))

    ballot = "\n".join(f"- {n} advocate: action={r.get('action')}, query={r.get('query')!r}, "
                       f"dx={r.get('dx')!r} ({r.get('why','')})" for n, r in proposals)
    coord_user = f"{obs}\n\nADVOCATE PROPOSALS:\n{ballot}\n\nReconcile into one action."
    rec = None
    for extra in ([], [{"role": "user", "content": "Return ONLY the JSON object."}]):
        try:
            rec = G._extract_json(llm.chat(
                [{"role": "system", "content": DEBATE_COORD + final_hint},
                 {"role": "user", "content": coord_user}] + extra, model=model, max_tokens=700))
            break
        except Exception:
            continue

    reasoning, differential = "", []
    if rec is None:
        action, query = _safe_fallback(env)
        reasoning = "(coordinator output unparseable; safe default.)"
    else:
        reasoning = rec.get("debate", "") or ""
        differential = rec.get("differential", []) or []
        a = rec.get("action")
        action = {"ask": "ask", "test": "order", "diagnose": "diagnose"}.get(a, "diagnose")
        query = (rec.get("diagnosis") if action == "diagnose" else rec.get("query")) or ""
        if not query:
            action, query = _safe_fallback(env)

    if final and action != "diagnose":                   # force a commit on the final turn
        query = (differential[0]["dx"] if differential and differential[0].get("dx")
                 else next((r.get("dx") for _, r in proposals if r.get("dx")), "undetermined"))
        action = "diagnose"
    return _apply(env, action, query, reasoning, differential, model=model)


def _orderable(env):
    t = env.orderable_tests()
    return f"Orderable tests: {t}" if t else "Order any diagnostic test by name (free text)."


_TAG_ALL = re.compile(r"<(question|test|diagnosis)>(.*?)</\1>", re.DOTALL | re.IGNORECASE)


def _parse_baseline_multi(text):
    """Parse the baseline XML, allowing MULTIPLE <test> (or <question>) tags per turn."""
    if not text:
        return None
    m = _TAG_ALL.findall(text)
    if not m:
        return None
    diags = [c.strip() for tg, c in m if tg.lower() == "diagnosis" and c.strip()]
    if diags:
        return "diagnose", diags[0]
    tests = [c.strip() for tg, c in m if tg.lower() == "test" and c.strip()]
    if tests:
        return "order", tests                      # a batch of tests this turn
    qs = [c.strip() for tg, c in m if tg.lower() == "question" and c.strip()]
    if qs:
        return "ask", qs[0]
    return None


def _safe_fallback(env):
    """A sensible next action when the model output can't be parsed (no cheating)."""
    if not env.asked:
        return "ask", "What is the history of present illness and key risk factors?"
    pool = env.orderable_tests()
    informative = [p for p in pool if getattr(env.case.panels.get(p, None), "informative", False)]
    if informative:
        return "order", min(informative, key=lambda p: env.case.panels[p].cost)
    if pool:
        return "order", pool[0]
    return "diagnose", "undetermined"


# Token budget for AGENT calls. Big enough that a reasoning model's <think> trace AND the
# actual answer (XML tags / JSON) both fit — otherwise the answer gets truncated away.
AGENT_MAX_TOKENS = 2200


def agent_turn(env, design, model=None, final=False):
    """Run ONE agent turn live and apply it to env. Returns a dict describing the turn."""
    label, system, kind = DESIGNS[design]
    if kind == "debate":                                 # genuine multi-agent (separate advocate calls)
        return _debate_turn(env, model=model, final=final)
    if final:
        system += ("\nThis is your final turn: you MUST diagnose now."
                   if kind == "baseline" else "\nThis is your final turn: action MUST be 'diagnose'.")
    # paper-faithful: a turn is one action TYPE, but a test action may batch several tests
    system += ("\nYou may order several tests in one turn by emitting multiple <test> tags."
               if kind == "baseline" else
               "\nFor a 'test' action you may order up to three discriminating tests at once; "
               "list them in 'query' separated by semicolons.")
    user = env.observation() + "\n\n" + _orderable(env) + "\nTake one action."
    messages = [{"role": "system", "content": system}, {"role": "user", "content": user}]

    reasoning, differential = "", []
    if kind == "baseline":
        # generous budget so a reasoning model's thinking + the answer both fit (else truncation
        # eats the <test>/<diagnosis> tags); thinking stays ON here — that's the accuracy lever.
        parsed = _parse_baseline_multi(llm.chat(messages, model=model, max_tokens=AGENT_MAX_TOKENS))
        if parsed is None:                                   # one retry, then safe fallback
            parsed = _parse_baseline_multi(llm.chat(
                messages + [{"role": "user", "content": "Output your tags now."}],
                model=model, max_tokens=AGENT_MAX_TOKENS))
        if parsed is None:
            action, query = _safe_fallback(env)
        else:
            action, query = parsed                           # query may be a list of tests
    else:
        rec = None
        for extra in ([], [{"role": "user", "content": "Return ONLY the JSON object, no prose."}]):
            try:
                rec = G._extract_json(llm.chat(messages + extra, model=model, max_tokens=AGENT_MAX_TOKENS))
                break
            except Exception:
                continue
        if rec is None:                                      # both attempts unparseable
            action, query = _safe_fallback(env)
            reasoning = "(panel output unparseable; took a safe default action.)"
        else:
            reasoning = rec.get("debate", "") or ""
            differential = rec.get("differential", []) or []
            a = rec.get("action")
            action = {"ask": "ask", "test": "order", "diagnose": "diagnose"}.get(a, "diagnose")
            query = (rec.get("diagnosis") if action == "diagnose" else rec.get("query")) or ""
            if action == "order":                            # allow a batch of tests
                tests = rec.get("tests") or query
                if isinstance(tests, str):
                    tests = [p.strip() for p in re.split(r"[;\n]+", tests) if p.strip()]
                query = tests if isinstance(tests, list) and tests else query
            if not query:
                action, query = _safe_fallback(env)

    if final and action != "diagnose":
        # weaker models often won't stop ordering — force a commit on the final turn so the
        # case is always scoreable. Prefer the panel's top differential; else ask for one guess.
        if differential and differential[0].get("dx"):
            query = differential[0]["dx"]
        else:
            try:
                guess = llm.chat(messages + [{"role": "user", "content":
                        "Stop testing and commit. Name the single most likely DISEASE/DIAGNOSIS (not a test), "
                        "in a few words. Reply with ONLY the diagnosis, no tags."}],
                        model=model, max_tokens=60, think=False)   # quick commit, no thinking
                guess = re.sub(r"<[^>]+>", "", guess).strip()        # strip any stray XML tags
                query = guess.split("\n")[0][:140] or "undetermined"
            except Exception:
                query = "undetermined"
        action = "diagnose"

    return _apply(env, action, query, reasoning, differential, model=model)


# --- Judge: the paper's 5-point Likert rubric (Table 1), run as a real LLM grader ---
JUDGE_SYSTEM = (
    "You are the Judge in a sequential-diagnosis benchmark. Compare the CANDIDATE diagnosis to the "
    "REFERENCE diagnosis and score 1-5 on this rubric (accept exact medical synonyms — the same "
    "disease entity under a different accepted name):\n"
    "5 = clinically identical, or a strictly MORE specific version (added detail must be directly related).\n"
    "4 = core disease correct; a secondary qualifier missing or slightly mis-specified; management largely unchanged.\n"
    "3 = correct general category but a MAJOR error in etiology/site/specificity, or a correct dx bundled with an unrelated one.\n"
    "2 = shares superficial features only; fundamentally misdirects the workup.\n"
    "1 = no meaningful overlap; wrong organ/system; following it would lead to harmful care.\n"
    "A score >= 4 counts as CORRECT. Reply with ONLY JSON: {\"score\": <1-5 int>, \"reason\": \"<one line>\"}."
)


def judge_llm(case, candidate, model=None):
    """Grade a candidate diagnosis with the rubric. Falls back to the offline keyword judge."""
    from demo_environment import judge_diagnosis
    msg = [{"role": "system", "content": JUDGE_SYSTEM},
           {"role": "user", "content": f"REFERENCE: {case.true_diagnosis}\nCANDIDATE: {candidate}\n"
            f"Case context: {case.abstract}\nScore:"}]
    try:
        rec = G._extract_json(llm.chat(msg, model=model, max_tokens=160, think=False))
        score = int(rec.get("score"))
        return {"score": max(1, min(5, score)), "reason": rec.get("reason", "")[:160]}
    except Exception:
        correct, detail = judge_diagnosis(case, candidate)   # offline fallback
        return {"score": 5 if correct else 2, "reason": detail}


def _apply(env, action, query, reasoning="", differential=None, model=None):
    """Apply one turn. `query` may be a LIST for 'order' (a batch of tests, paper-faithful)."""
    if action == "ask":
        q = query[0] if isinstance(query, list) else query
        step = env.ask_question(q)
        disp, finding, cost, turn, done = q, step.response, step.cost, step.turn, False
    elif action == "order":
        names = query if isinstance(query, list) else [query]
        names = [n for n in (s.strip() for s in names) if n][:3]   # paper: up to 3 tests/round
        if not names:
            names = [str(query)]
        steps = [env.order_test(n) for n in names]
        orders = [{"name": n, "finding": s.response, "cost": s.cost} for n, s in zip(names, steps)]
        disp = ", ".join(names)
        finding = "\n\n".join(s.response for s in steps)
        cost = sum(s.cost for s in steps)
        turn, done = steps[-1].turn, False
    else:
        q = query[0] if isinstance(query, list) else query
        step = env.diagnose(q)
        disp, finding, cost, turn, done = q, step.response, step.cost, step.turn, True
    out = {"turn": turn, "action": action, "query": disp,
           "finding": finding, "cost": cost, "total_cost": round(env.total_cost),
           "done": done, "correct": None, "reasoning": reasoning,
           "differential": differential, "ordered": sorted(env.ordered),
           "n_questions": len(env.asked), "n_tests": len(env.ordered)}
    if action == "order":
        out["orders"] = orders                 # per-test {name, finding, cost} for the batch
    if done:                                   # rubric Judge replaces the keyword verdict
        j = judge_llm(env.case, disp)          # fixed judge (default OLLAMA_MODEL), not the agent model
        out["correct"] = j["score"] >= 4
        out["judge_score"] = j["score"]
        out["judge_reason"] = j["reason"]
        out["finding"] = f"Judge {j['score']}/5 — {j['reason']}"
    return out


MAX_TURNS = 8


def refined_case_ids():
    """The cases we've refined — the ONLY ones shown in the UI: split CPC presentations + all MIMIC
    cases. Empty set = nothing refined yet, so fall back to showing everything."""
    ids = set(MIMIC_BY_ID)
    try:
        ids |= set(json.load(open(os.path.join(HERE, "data", "cpc_presentations.json"))))
    except Exception:
        pass
    return ids


# ---- routes ----------------------------------------------------------------

@app.get("/")
def index():
    # Participant link: /?pid=ABC attributes this browser to a participant. No pid -> generate
    # an anonymous one so nothing is ever unattributed.
    pid = request.args.get("pid") or session.get("pid") or ("anon-" + uuid.uuid4().hex[:8])
    session["pid"] = pid
    store.upsert_participant(pid)
    store.ensure_session(_sid(), pid, request.headers.get("User-Agent"))
    refined = refined_case_ids()                  # show only the refined cases (if any refined yet)
    recorded_modes = {}                           # cases that actually have a recording to replay
    for _model, _d, _fp, cid, run in iter_runs():
        if refined and cid not in refined:
            continue
        recorded_modes.setdefault(cid, run.get("mode") or "cpc")
    recorded = sorted(recorded_modes)
    cases = [c for c in all_case_options() if not refined or c["id"] in refined]
    return render_template("index.html",
                           cases=cases,
                           recorded=recorded,
                           recorded_modes=recorded_modes,
                           backend=llm.active_model(),
                           live=llm.detect_backend() != "stub",
                           models=MODELS,
                           pid=pid,
                           consented=True,  # consent gate disabled (advisor/demo share)
                           designs=[{"id": k, "label": v[0]} for k, v in DESIGNS.items()])


@app.get("/api/models")
def api_models():
    """Models that have replayable recordings, for the UI model picker. One entry per model
    slug (new-layout dir or legacy file) with its recorded case ids + modes. Backups (_*),
    SAMPLE padding, and error-only models are hidden. Sorted by coverage (most cases first)."""
    refined = refined_case_ids()                         # UI shows only the refined cases
    by = {}                                              # slug -> {cases:{cid:mode}, designs:set, ok:bool}
    for model, design, fp, cid, run in iter_runs():
        if model.startswith("_") or cid.startswith("SAMPLE") or (refined and cid not in refined):
            continue
        m = by.setdefault(model, {"cases": {}, "designs": set(), "ok": False})
        m["cases"][cid] = run.get("mode") or "cpc"
        m["designs"].add(design)
        turns = run.get("turns") or []
        if turns and not any(t.get("error") for t in turns):
            m["ok"] = True
    out = []
    for slug, m in by.items():
        if not m["ok"]:                                  # skip models whose runs are all errors
            continue
        out.append({"slug": slug, "n_cases": len(m["cases"]), "designs": sorted(m["designs"]),
                    "cases": sorted(m["cases"]), "modes": m["cases"]})
    out.sort(key=lambda x: -x["n_cases"])
    return jsonify({"models": out})


def _recordings_path_for(model):
    """Default recordings.json, or a specific model's file under data/recordings/<slug>.json."""
    if model:
        import re as _re
        slug = _re.sub(r"[^a-z0-9._-]+", "-", model.lower()).strip("-")
        return os.path.join(HERE, "data", "recordings", slug + ".json")
    return RECORDINGS_PATH


@app.get("/api/case")
def api_case():
    """What the model is GIVEN for a case: the turn-0 presentation (history + exam), plus the
    full vignette for reviewers. Independent of recordings, so the UI can show it immediately."""
    cid = request.args.get("case")
    try:
        case, mode = load_any(cid)
    except Exception:
        return jsonify({"error": f"unknown case {cid}"}), 404
    presentation = (getattr(case, "presentation", "") or "").strip() or case.abstract
    return jsonify({"case_id": cid, "mode": mode, "abstract": case.abstract,
                    "presentation": presentation, "full_case": full_vignette(case)})


@app.get("/api/recording")
def api_recording():
    """Return a pre-recorded agent run for (case, design[, model]) — static replay, no live calls."""
    cid = request.args.get("case")
    design = request.args.get("design", "single")
    model = request.args.get("model") or DEFAULT_MODEL
    rec = None
    nf = run_file(model, design)                  # new content-keyed layout first
    if os.path.exists(nf):
        try:
            rec = json.load(open(nf)).get(cid)
        except Exception:
            rec = None
    if rec is None:                               # legacy aggregate fallback
        path = _recordings_path_for(request.args.get("model"))
        try:
            with open(path) as f:                 # re-read so the recorder's progress shows live
                recs = json.load(f)
        except Exception:
            recs = RECORDINGS
        rec = recs.get(cid, {}).get(design)
    if not rec:
        return jsonify({"error": f"no recording for {cid} / {design}"}), 404
    return jsonify(rec)


def _auto_noharm(appr, harm):
    """Server-side NOHARM auto-score (1-9) — stored for human-vs-auto agreement, never shown."""
    if appr >= 0.6:
        return 9 if appr >= 0.85 else 8 if appr >= 0.70 else 7
    if appr <= 0.4:
        return 1 if harm >= 0.70 else 2 if harm >= 0.45 else 3
    return 6 if appr >= 0.55 else 4 if appr <= 0.45 else 5


def _score_features(case_id, test):
    """(appropriateness, harm, cost, auto_noharm) for a test in a case — or Nones if unscorable."""
    try:
        case, _ = load_any(case_id)
        s = score_recommendation(case, test)
        return round(s.appropriateness, 3), round(s.harm, 3), s.cost, _auto_noharm(s.appropriateness, s.harm)
    except Exception:
        return None, None, None, None


@app.post("/api/consent")
def api_consent():
    """Record that this participant consented. Required before any task data is meaningful."""
    pid = _pid()
    if not pid:
        return jsonify({"error": "no participant"}), 400
    store.set_consent(pid)
    return jsonify({"ok": True, "pid": pid})


@app.post("/api/grade")
def api_grade():
    """Persist one clinician grade. The auto-scorer is computed and stored (for human-vs-auto
    agreement) but NEVER returned to the client, so it can't bias grading. Idempotent."""
    rec = request.json or {}
    appr, harm, cost, auto = _score_features(rec.get("case_id"), rec.get("test"))
    try:
        store.log_grade(client_event_id=rec.get("event_id"), **_attribution(),
                        case_id=rec.get("case_id"), design=rec.get("design"), test=rec.get("test"),
                        grade=rec.get("grade"), appropriateness=rec.get("appropriateness"),
                        harm=rec.get("harm"), latency_ms=rec.get("latency_ms"),
                        auto_appropriateness=appr, auto_harm=harm, auto_cost=cost, auto_noharm=auto)
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True})


@app.post("/api/sim_event")
def api_sim_event():
    """Log one Simulation alert decision with the RL state/action/features: recommendation
    appropriateness/harm/cost, clinician action, latency, time-in-shift, the running
    alert-fatigue (interruption count) and sequence index. Idempotent."""
    rec = request.json or {}
    appr, harm, cost, auto = _score_features(rec.get("case_id"), rec.get("test"))
    try:
        store.log_sim(client_event_id=rec.get("event_id"), **_attribution(),
                      case_id=rec.get("case_id"), test=rec.get("test"), choice=rec.get("choice"),
                      latency_ms=rec.get("latency_ms"), shift_min=rec.get("shift_min"),
                      seq=rec.get("seq"), fatigue=rec.get("fatigue"),
                      appropriateness=appr, harm=harm, cost=cost, auto_noharm=auto)
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True})


@app.post("/api/clin_event")
def api_clin_event():
    """Log one clinician benchmark turn: action, decision-time, running cost, outcome. Idempotent."""
    rec = request.json or {}
    try:
        store.log_bench(client_event_id=rec.get("event_id"), **_attribution(),
                        case_id=rec.get("case_id"), action=rec.get("action"), query=rec.get("query"),
                        latency_ms=rec.get("latency_ms"), turn=rec.get("turn"),
                        total_cost=rec.get("total_cost"), correct=rec.get("correct"),
                        judge_score=rec.get("judge_score"))
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    return jsonify({"ok": True})


ADMIN_TOKEN = os.environ.get("STUDY_ADMIN_TOKEN")


def _admin_ok():
    """Researcher-only endpoints. If an admin token is set (e.g. when exposed via a tunnel),
    REQUIRE it — don't trust apparent-localhost, since a tunnel makes every request look local.
    With no token set, fall back to localhost-only (fine for local dev)."""
    if ADMIN_TOKEN:
        return (request.args.get("token") == ADMIN_TOKEN
                or request.headers.get("X-Admin-Token") == ADMIN_TOKEN)
    return request.remote_addr in ("127.0.0.1", "::1", None)


_ABBR = {"single": "LLM", "maidxo": "LLM-Roles", "debate": "LLM-Multi"}


@app.get("/api/stats")
def api_stats():
    """Benchmark points for the Pareto plot: one point per (model x agent design), aggregated
    over cases, split by dataset mode (cpc / ehr / all). Scans every per-model recording file."""
    refined = refined_case_ids()                         # Results reflect only the refined cases
    by = {}                                              # (model, design, mode) -> rows
    for model, d, fp, cid, run in iter_runs():
        if cid.startswith("SAMPLE") or model.startswith("_"):   # skip demo padding + backup/error dumps
            continue
        if d not in DESIGNS or (refined and cid not in refined):
            continue
        turns = run.get("turns") or []
        dx = next((t for t in turns if t.get("action") == "diagnose"), None)
        if not dx:
            continue
        last = turns[-1]
        meta = run.get("meta") or {}
        conc = meta.get("concordance") or {}
        by.setdefault((model, d, run.get("mode", "ehr")), []).append(
            {"correct": bool(dx.get("correct")), "score": dx.get("judge_score"),
             "cost": last.get("total_cost"), "turns": len(turns), "tests": last.get("n_tests"),
             "tokens": meta.get("total_tokens"), "secs": meta.get("duration_s"),
             "recall": conc.get("recall"), "precision": conc.get("precision")})

    def summ(rows):
        n = len(rows)
        if not n:
            return {"n": 0, "accuracy": 0, "accuracy_ci": 0, "judge": 0}

        def stat(k, dp):                                # mean + standard error over present values
            vals = [r[k] for r in rows if r.get(k) is not None]
            if not vals:
                return None, None
            m = sum(vals) / len(vals)
            sd = (sum((v - m) ** 2 for v in vals) / len(vals)) ** 0.5
            return round(m, dp), round(sd / len(vals) ** 0.5, max(dp, 1))

        p = sum(1 for r in rows if r["correct"]) / n
        out = {"n": n, "accuracy": round(100 * p),
               "accuracy_ci": round(100 * 1.96 * (p * (1 - p) / n) ** 0.5),   # 95% CI half-width (pts)
               "judge": stat("score", 2)[0]}
        for k, dp in (("cost", 0), ("turns", 1), ("tests", 1), ("tokens", 0), ("secs", 1),
                      ("recall", 3), ("precision", 3)):
            out[k], out[k + "_sem"] = stat(k, dp)
        return out

    md = {}                                              # (model, design) -> {mode: rows}
    for (model, d, mode), rows in by.items():
        md.setdefault((model, d), {})[mode] = rows
    modes = {"cpc": [], "mimic": [], "all": []}
    for (model, d), mm in sorted(md.items()):
        allrows = [r for rows in mm.values() for r in rows]
        for mode, rows in (("cpc", mm.get("cpc", [])), ("mimic", mm.get("mimic", [])), ("all", allrows)):
            if not rows:
                continue
            ms = model.replace("-instruct", "")
            for pref in ("meta-llama-", "openai-", "google-", "anthropic-", "mistralai-", "qwen-", "deepseek-"):
                if ms.startswith(pref):
                    ms = ms[len(pref):]
            modes[mode].append({"model": model, "model_short": ms[:18],
                                "design": d, "label": DESIGNS.get(d, (d,))[0], "abbr": _ABBR.get(d, d),
                                **summ(rows)})
    return jsonify({"modes": modes, "n_models": len({m for m, _ in md})})


_SPECIALTY = [
    ("Infectious", r"infect|sepsis|abscess|meningitis|encephalitis|tuberculos|pneumon|endocarditis|"
                   r"virus|viral|bacteri|fungal|cryptococc|malaria|\bhiv\b|hepatitis|cellulitis"),
    ("Onc / Heme", r"lymphoma|leukemia|carcinoma|sarcoma|cancer|tumor|myeloma|metasta|neoplas|melanoma|"
                   r"blastoma|malignan|histiocytosis|lymphoprolifer"),
    ("Cardiovascular", r"cardi|myocard|\bheart\b|aortic|vascul|embol|infarct|arrhythm|valv|pericard"),
    ("Neurology", r"encephal|neuro|stroke|seizure|sclerosis|myelo|cerebr|spinal|parkinson|dementia|angiitis"),
    ("Renal", r"renal|nephr|kidney|glomerul"),
    ("GI / Hepatic", r"hepat|liver|pancreat|colitis|bowel|gastr|crohn|biliary|cirrhos|esophag"),
    ("Pulmonary", r"pulmonar|\blung\b|pleural|respiratory|asthma|copd|sarcoidosis"),
    ("Endocrine", r"diabet|thyroid|adrenal|pituitary|endocr|prolactin|ketoacidosis"),
    ("Rheum / Immune", r"vasculitis|lupus|arthritis|autoimmune|amyloid|rheum|immune|granulomato"),
]
_COSTCAT = [
    ("Imaging", r"\bct\b|\bmri\b|x[\s-]?ray|radiograph|ultrasound|echo|angiogra|\bpet\b|scan|mammogram"),
    ("Procedure", r"biopsy|bronchoscopy|endoscopy|colonoscopy|lumbar puncture|aspirat|marrow|\blp\b"),
    ("Genetic/Path", r"flow cytometry|cytogenet|genetic|\bpcr\b|sequenc|immunohist|patholog|molecular|\bfish\b"),
    ("Micro/Serol", r"culture|gram stain|serolog|antibody|antigen|\btiter\b|microbiolog"),
]


def _specialty(dx):
    d = (dx or "").lower()
    for name, pat in _SPECIALTY:
        if re.search(pat, d):
            return name
    return "Other"


def _costcat(name):
    n = (name or "").lower()
    for cat, pat in _COSTCAT:
        if re.search(pat, n):
            return cat
    return "Labs"


@app.get("/api/analysis")
def api_analysis():
    """Extra SDBench-style breakdowns from the recorded benchmark (CPC, one model):
    error-type distribution (Judge 1-5), cost composition by test category, accuracy by specialty.
    Defaults to the model with the most CPC runs; override with ?model=<slug>."""
    rows = [(m, d, cid, run) for m, d, fp, cid, run in iter_runs()
            if run.get("mode") == "cpc" and not cid.startswith("SAMPLE")]
    target = request.args.get("model")
    if not target and rows:                          # pick the model with the most CPC runs
        from collections import Counter
        target = Counter(m for m, *_ in rows).most_common(1)[0][0]
    rows = [r for r in rows if r[0] == target]
    agg = {}
    for _m, d, cid, run in rows:
        ts = run.get("turns") or []
        dx = next((t for t in ts if t.get("action") == "diagnose"), None)
        if not dx:
            continue
        D = agg.setdefault(d, {"n": 0, "err": [0, 0, 0, 0, 0], "spec": {}, "cost": {}})
        D["n"] += 1
        js = min(5, max(1, dx.get("judge_score") or 1))
        D["err"][js - 1] += 1
        sp = _specialty(run.get("true_dx"))
        s = D["spec"].setdefault(sp, [0, 0]); s[1] += 1; s[0] += 1 if dx.get("correct") else 0
        for t in ts:
            if t.get("action") == "ask" and (t.get("cost") or 0) > 0:
                D["cost"]["Visits"] = D["cost"].get("Visits", 0) + (t.get("cost") or 0)
            if t.get("action") == "order":
                for o in (t.get("orders") or []):
                    c = _costcat(o.get("name", ""))
                    D["cost"][c] = D["cost"].get(c, 0) + (o.get("cost") or 0)

    out = {"designs": [], "model": target}
    for d in DESIGNS:                                    # the three current designs, in order
        if d not in agg:
            continue
        D = agg[d]; n = D["n"] or 1
        out["designs"].append({
            "id": d, "label": DESIGNS[d][0], "n": D["n"],
            "errors": [round(100 * x / n) for x in D["err"]],
            "specialty": [{"name": k, "acc": round(100 * v[0] / v[1]) if v[1] else 0, "n": v[1]}
                          for k, v in sorted(D["spec"].items(), key=lambda kv: -kv[1][1])],
            "cost": {k: round(v / n) for k, v in sorted(D["cost"].items(), key=lambda kv: -kv[1])},
        })
    return jsonify(out)


@app.get("/api/budget")
def api_budget():
    """Cost-budget sweep -> per (model, design, cap): accuracy and avg actual spend (the SDBench curve)."""
    path = os.path.join(HERE, "data", "budget_sweep.json")
    try:
        data = json.load(open(path))
    except Exception:
        return jsonify({"models": []})
    out = {"models": []}
    for model, caps in data.items():
        designs = {}
        for cap, dd in caps.items():
            for d, cases in dd.items():
                rows = []
                for cid, run in cases.items():
                    ts = (run or {}).get("turns") or []
                    dx = next((t for t in ts if t.get("action") == "diagnose"), None)
                    if not dx:
                        continue
                    rows.append((bool(dx.get("correct")), ts[-1].get("total_cost") or 0))
                if not rows:
                    continue
                n = len(rows)
                designs.setdefault(d, []).append(
                    {"cap": cap, "n": n,
                     "accuracy": round(100 * sum(1 for c, _ in rows if c) / n),
                     "cost": round(sum(c for _, c in rows) / n)})
        for d in designs:
            designs[d].sort(key=lambda p: p["cost"])
        if designs:
            out["models"].append({"model": model, "model_short": model.replace("-instruct", "")[:18],
                                   "designs": [{"id": d, "label": DESIGNS.get(d, (d,))[0], "points": p}
                                               for d, p in designs.items()]})
    return jsonify(out)


@app.get("/api/ablation")
def api_ablation():
    """Panel role ablation -> per removed role: accuracy and delta vs the full panel."""
    path = os.path.join(HERE, "data", "ablation.json")
    try:
        data = json.load(open(path))
    except Exception:
        return jsonify({"models": []})
    out = {"models": []}
    for model, variants in data.items():
        rows = []
        for key, v in variants.items():
            accs = []
            for cid, r in (v.get("runs") or {}).items():
                ts = (r or {}).get("turns") or []
                dx = next((t for t in ts if t.get("action") == "diagnose"), None)
                if dx:
                    accs.append(bool(dx.get("correct")))
            if not accs:
                continue
            rows.append({"key": key, "label": v.get("label", key), "n": len(accs),
                         "accuracy": round(100 * sum(accs) / len(accs))})
        if not rows:
            continue
        base = next((r["accuracy"] for r in rows if r["key"] == "full"), 0)
        for r in rows:
            r["delta"] = r["accuracy"] - base
        rows = ([r for r in rows if r["key"] == "full"] +
                sorted([r for r in rows if r["key"] != "full"], key=lambda r: r["accuracy"]))
        out["models"].append({"model": model, "model_short": model.replace("-instruct", "")[:18],
                              "base": base, "variants": rows})
    return jsonify(out)


@app.get("/api/counts")
def api_counts():
    """Live row counts per table — for verifying data is being captured during a session."""
    if not _admin_ok():
        return jsonify({"error": "unauthorized"}), 401
    return jsonify(store.counts())


@app.get("/api/export")
def api_export():
    """Download a table as CSV (grade | sim_event | bench_turn | participant | session)."""
    if not _admin_ok():
        return jsonify({"error": "unauthorized"}), 401
    table = request.args.get("table", "grade")
    try:
        csv_text = store.export_csv(table)
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    from flask import Response
    return Response(csv_text, mimetype="text/csv",
                    headers={"Content-Disposition": f"attachment; filename={table}.csv"})


@app.post("/api/new")
def api_new():
    case_id = request.json["case_id"]
    gatekeeper = request.json.get("gatekeeper", "auto")
    case, mode = load_any(case_id)
    env = _make_env(case, gatekeeper)
    SESSIONS[_sid()] = {"case_id": case_id, "mode": mode, "env": env,
                        "design": request.json.get("design", "single"),
                        "model": request.json.get("model") or DEFAULT_MODEL,
                        "gatekeeper": gatekeeper}
    return jsonify({"abstract": case.abstract, "true_dx": case.true_diagnosis,
                    "full_case": full_vignette(case),
                    "gatekeeper": "llm" if env.llm_gatekeeper else "rule",
                    "mode": mode, "orderable": env.orderable_tests(),
                    "case_id": case_id})


@app.post("/api/manual")
def api_manual():
    st = _state()
    if not st:
        return jsonify({"error": "no session; pick a case"}), 400
    env = st["env"]
    if env.done:
        return jsonify({"done": True, "noop": True})
    action = request.json["action"]            # ask | order | diagnose
    query = request.json.get("query", "").strip()
    if not query:
        return jsonify({"error": "empty query"}), 400
    try:
        return jsonify(_apply(env, action, query, model=st.get("model")))
    except Exception as e:
        return jsonify({"error": f"{type(e).__name__}: {e}"}), 500


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "5050"))          # 5000 collides with macOS AirPlay Receiver
    prod = os.environ.get("STUDY_PROD", "").lower() in ("1", "true", "yes")
    print(f"\n  LLM backend: {llm.active_model()}  (live={llm.detect_backend() != 'stub'})")
    print(f"  open http://127.0.0.1:{port}\n")
    if prod:                                             # study mode: stable server, no debugger page
        if app.secret_key == "demo-not-secret":
            raise SystemExit("Refusing to run prod with the default secret. Set STUDY_SECRET=<random>.")
        host = os.environ.get("STUDY_BIND", "127.0.0.1")  # localhost by default; opt in to expose
        if host != "127.0.0.1":
            print(f"  ⚠ binding {host} — put HTTPS + auth (reverse proxy) in front; set STUDY_ADMIN_TOKEN.")
        from waitress import serve as _serve
        print("  production server (waitress, debug off) — STUDY_PROD=1\n")
        _serve(app, host=host, port=port, threads=8)
    else:
        app.run(debug=True, port=port, use_reloader=False)
